openapi: 3.0.3

info:
  title: CPCL API
  version: 1.0.0
  description: CPCL Service API Documentation

servers:
  - url: http://localhost:8000
  - url: https://cpcl.dinanfarm.com

paths:
  /api/auth/login:
    $ref: './paths/auth.yaml#/login'
  /api/auth/logout:
    $ref: './paths/auth.yaml#/logout'
  /api/group-fields:
    $ref: './paths/group-fields.yaml#/list'
  /api/group-fields/store:
    $ref: './paths/group-fields.yaml#/store'
  /api/group-fields/{id}/show:
    $ref: './paths/group-fields.yaml#/detail'
  /api/group-fields/{id}/update:
    $ref: './paths/group-fields.yaml#/update'
  /api/group-fields/{id}/delete:
    $ref: './paths/group-fields.yaml#/delete'
  /api/cpcl-documents:
    $ref: './paths/cpcl-documents.yaml#/list'
  /api/cpcl-documents/store:
    $ref: './paths/cpcl-documents.yaml#/store'
  /api/cpcl-documents/{id}/show:
    $ref: './paths/cpcl-documents.yaml#/detail'
  /api/cpcl-documents/{id}/update:
    $ref: './paths/cpcl-documents.yaml#/update'
  /api/cpcl-documents/{id}/status:
    $ref: './paths/cpcl-documents.yaml#/updateStatus'
  /api/cpcl-documents/{id}/delete:
    $ref: './paths/cpcl-documents.yaml#/delete'

  /api/cpcl-applicants:
      $ref: './paths/cpcl-applicants.yaml#/list'
  /api/cpcl-applicants/store:
      $ref: './paths/cpcl-applicants.yaml#/store'

  /api/cpcl-applicants/{id}/show:
      $ref: './paths/cpcl-applicants.yaml#/detail'
  /api/cpcl-applicants/{id}/update:
      $ref: './paths/cpcl-applicants.yaml#/update'
  /api/cpcl-applicants/{id}/delete:
      $ref: './paths/cpcl-applicants.yaml#/delete'
  /api/cpcl-answers:
      $ref: './paths/cpcl-answers.yaml#/store'
  /api/cpcl-answers/{cpcl_document_id}:
      $ref: './paths/cpcl-answers.yaml#/detail'
  /api/cpcl-documents/{cpcl_document_id}/fishing-vessels:
      $ref: './paths/cpcl-fishing-vessels.yaml#/list'
  /api/cpcl-documents/{cpcl_document_id}/fishing-vessels/store:
      $ref: './paths/cpcl-fishing-vessels.yaml#/store'
  /api/cpcl-documents/{cpcl_document_id}/fishing-vessels/update:
      $ref: './paths/cpcl-fishing-vessels.yaml#/update'

components:
  schemas:
    $ref: './components/schemas.yaml'
  responses:
    $ref: './components/responses.yaml'
  securitySchemes:
    $ref: './components/security.yaml'
